version: "3"
services:

  endpoint:
    build: ./src
    ports:
        - "5000:5000"
    depends_on:
        -  postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "1234"
    ports:
        - 5432:5432
