version: "3" #docker-compose version
services: #the containers in the network

  endpoint:
    build: ./src
    ports:
        - "5000:5000"
    depends_on:
        -  postgres
  postgres:
    image: postgres #if using an existing image
    environment:
      POSTGRES_PASSWORD: "1234" # specify individual env variables.
    ports:
        - 5432:5432
